<a href="https://colab.research.google.com/github/jcuesta123/TFM-RL/blob/main/helicopter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First approach of the code of helicopter

In [51]:
import numpy as np
import math
import random


In [123]:
#helicopter parameters
g = 10
m_h = 1
deltaT = 0.1

In [118]:
max_action_space = np.array([2*m_h*g, math.pi/4])
min_action_space = np.array([0, -math.pi/4])
print(max_action_space, ' -->  Max Traction (N) and max angle (rad)')
print(min_action_space, ' -->  Min Traction (N) and min angle (rad)')

[20.          0.78539816]  -->  Max Traction (N) and max angle (rad)
[ 0.         -0.78539816]  -->  Min Traction (N) and min angle (rad)


In [147]:
observation_space = np.array([0., 0., 0., 0., True, False])
print(observation_space, ' -->  x, y, v_x, v_y, floor_contact, lateral_contact')

[0. 0. 0. 0. 1. 0.]  -->  x, y, v_x, v_y, floor_contact, lateral_contact


In [102]:
#to make it more realistic, it only can vary its controls  smoothly, through some discrete levels
def select_action(command):

  command = np.array(command)
  new_command = command + np.random.randint(-1, 2, size=2) * max_action_space/10

  return new_command

In [141]:
#environment, based on pyhsics, num. computation and conditionals
def environment(state, command):
  #Forces
  a_x = command[0]*math.sin(command[1])/m_h
  a_y = command[0]*math.cos(command[1])/m_h - g

  #Velocities
  state[2] = state[2] + deltaT*a_x
  state[3] = state[3] + deltaT*a_y

  #Positions
  state[0] = state[0] + deltaT*state[2]
  state[1] = state[1] + deltaT*state[3]

  #Contacts

  reward = 1
  return state, reward

In [148]:
print(observation_space, max_action_space)
print('-----------------------------------')
environment(observation_space, max_action_space)

[0. 0. 0. 0. 1. 0.] [20.          0.78539816]
-----------------------------------


(array([0.14142136, 0.04142136, 1.41421356, 0.41421356, 1.        ,
        0.        ]),
 1)